main: com.artemis.the.gr8.playerstats.core.Main
name: PlayerStats
version: 2.3
api-version: 1.21
description: adds commands to view player statistics in chat
author: Artemis_the_gr8
softdepend:
  - PlaceholderAPI
commands:
  statistic:
    aliases:
      - stat
      - stats
    description: show player statistics in private chat
    usage: "§6/stat info"
    permission: playerstats.stat
  statisticshare:
    aliases:
      - statshare
      - statsshare
    description: share last stat lookup in chat
    usage: "§6/This command can only be executed by clicking the \"share\" button in /stat results. 
    If you don't see this button, you don't have share-permission, or sharing is turned off."
    permission: playerstats.share
  statisticreload:
    aliases:
      - statreload
      - statsreload
    description: reloads the config
    usage: "§6/statreload"
    permission: playerstats.reload
  statisticexclude:
    aliases:
      - statexclude
      - statsexclude
    description: hide this player's statistics from /stat results
    usage: "§6/statexclude info"
    permission: playerstats.exclude
  top:
    description: Show top player statistics for approved stats
    usage: "§6/top <statistic_alias>"
    permission: playerstats.top
  statadmin:
    description: Manage PlayerStats approved statistics
    usage: "§6/statadmin <addapproved|removeapproved|listapproved> [options]"
    permission: playerstats.admin
permissions:
  playerstats.stat:
    description: allows usage of /statistic
    default: true
  playerstats.share:
    description: allows sharing stats in chat
    default: true
  playerstats.exclude:
    description: allows usage of /statexclude
    default: op
  playerstats.reload:
    description: allows usage of /statreload
    default: op
  playerstats.top:
    description: allows usage of /top
    default: true
  playerstats.admin:
    description: allows usage of /statadmin
    default: op